from endpoints.invoice import Invoice
from endpoints.login import Login
from endpoints.spec import Spec
from endpoints.sql import SQL
from endpoints.sync import Sync
from endpoints.insert import Insert
from endpoints.upload import Upload
from endpoints.insertGeneric import InsertGeneric
from endpoints.mock import Mock